### ISSUE TITLE
Generating an avatar based on a photo via API

### ISSUE THREAD

**Issue by yaroslav-perec** [readyplayerme/Example-iframe#6]
Hi!

I don't know if this is the right place to ask, but still, is it possible to generate an avatar only through the API? For example, you have a photo and want to generate an avatar by sending a request to some server without any interaction with an app interface

**Comment by tiivik** [comment]
> Hi!
> 
> I don't know if this is the right place to ask, but still, is it possible to generate an avatar only through the API? For example, you have a photo and want to generate an avatar by sending a request to some server without any interaction with an app interface

Hi @yaroslav-perec, thanks for the request! We don't currently have plans to expose that API though.
