### ISSUE TITLE
Feature request: Add API for auto choose the option.

### ISSUE THREAD

**Issue by albirrkarim** [readyplayerme/Example-iframe#9]
![](https://user-images.githubusercontent.com/1441981/174016962-2c63b9a5-2f06-4bd6-8cf7-4a0cf7096971.png)

I want to readyplayer.me iframe auto exporting glb url without showing the option email sign in.

I hope It can be set by add more URL params like in this configuration list
https://docs.readyplayer.me/ready-player-me/integration-guides/web#configuration

Thank you

**Comment by tiivik** [comment]
Hi @albirrkarim! Request to remove this can be submitted once [partnering up](https://partnerships.readyplayer.me/) with Ready Player Me.
